spring:

  servlet:
    session:
      tracking-modes : cookie
      timeout : 3600

    multipart:
      max-file-size: 15MB
      max-request-size: 100MB



  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://aws-rds.cyeqzizjffgt.ap-northeast-2.rds.amazonaws.com/hair_review
#    username: admin
#    password: kkt1326!
    url: jdbc:h2:tcp://localhost/~/hair
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100



logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

server:
  port: 3000

kakao:
  url: https://kapi.kakao.com/v2/user/me

cloud:
  aws:
    s3:
      bucket: howhair-user-image-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAZROTTVYQWJ4SYIPL
      secretKey: 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

